// Simple backend scaffold for Wasti AI — provides endpoints for LLM proxy and developer patch generation.
// WARNING: This scaffold is intentionally minimal. Do NOT run this in production without securing secrets.

require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const axios = require('axios');
const cors = require('cors');
const { Octokit } = require('@octokit/rest');

const app = express();
app.use(cors());
app.use(bodyParser.json({ limit: '1mb' }));

const PORT = process.env.PORT || 8080;

const octokit = process.env.BACKEND_GITHUB_PAT ? new Octokit({ auth: process.env.BACKEND_GITHUB_PAT }) : null;

app.get('/health', (req, res) => {
  res.json({ status: 'ok', time: Date.now() });
});

// /llm: simple passthrough to configured provider. For safety, this should be a backend that holds keys and rate limits.
app.post('/llm', async (req, res) => {
  try {
    const { provider = 'openai', payload = {} } = req.body;
    if (provider === 'openai') {
      if (!process.env.OPENAI_API_KEY) return res.status(500).json({ error: 'OpenAI key not configured' });
      const resp = await axios.post('https://api.openai.com/v1/chat/completions', payload, {
        headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}` }
      });
      return res.json(resp.data);
    }

    // Placeholder for other providers (Gemini, Anthropic, etc.)
    return res.status(400).json({ error: 'Provider not supported yet' });
  } catch (err) {
    console.error(err?.response?.data || err.message || err);
    res.status(500).json({ error: 'LLM request failed', detail: err?.response?.data || err.message });
  }
});

// /dev/patch: receive a request to generate a code patch (prompt + target files) and create a PR.
// For now, this endpoint will create a branch and open a PR with a placeholder body. It does not modify files until you
// provide the generated patch content. Implementations should validate and sanitize patches before committing.
app.post('/dev/patch', async (req, res) => {
  try {
    if (!octokit) return res.status(500).json({ error: 'GitHub PAT not configured on server' });
    const { owner, repo, base = 'main', title = 'Wasti Dev Patch', body = 'Automated patch generated by Wasti Assistant', changes = [] } = req.body;
    if (!owner || !repo) return res.status(400).json({ error: 'owner and repo required' });

    // 1. create branch from base
    const baseRef = `heads/${base}`;
    const mainRef = await octokit.git.getRef({ owner, repo, ref: baseRef });
    const baseSha = mainRef.data.object.sha;

    const branchName = `wasti/patch-${Date.now()}`;
    await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branchName}`, sha: baseSha });

    // 2. For safety, do not write file changes unless 'changes' provided as array of {path, content}
    const commitMessage = title;
    if (Array.isArray(changes) && changes.length > 0) {
      // Create blobs and tree
      const blobs = [];
      for (const c of changes) {
        const blob = await octokit.git.createBlob({ owner, repo, content: c.content, encoding: 'utf-8' });
        blobs.push({ path: c.path, mode: '100644', type: 'blob', sha: blob.data.sha });
      }

      // Get base tree
      const baseCommit = await octokit.git.getCommit({ owner, repo, commit_sha: baseSha });
      const newTree = await octokit.git.createTree({ owner, repo, tree: blobs, base_tree: baseCommit.data.tree.sha });
      const newCommit = await octokit.git.createCommit({ owner, repo, message: commitMessage, tree: newTree.data.sha, parents: [baseSha] });
      // Update ref
      await octokit.git.updateRef({ owner, repo, ref: `refs/heads/${branchName}`, sha: newCommit.data.sha });
    }

    // 3. Create PR
    const pr = await octokit.pulls.create({ owner, repo, title, head: branchName, base, body });

    return res.json({ prUrl: pr.data.html_url, branch: branchName });
  } catch (err) {
    console.error('dev/patch failed', err?.response?.data || err.message || err);
    res.status(500).json({ error: 'dev/patch failed', detail: err?.response?.data || err.message });
  }
});

app.listen(PORT, () => {
  console.log(`Wasti backend listening on port ${PORT}`);
});
