package com.example.data.agent.runtime

import android.content.Context
import java.io.File
import java.nio.charset.StandardCharsets

/**
 * Stage 1: Software Filesystem Boundary.
 * All agentic workspace operations MUST occur strictly within:
 * context.filesDir/wasti_workspace/
 *
 * SECURITY NOTICE:
 * WorkspaceManager provides a software-level path boundary.
 * It canonicalizes all paths and rejects directory traversal or external path escapes.
 * It is NOT an OS-level kernel sandbox.
 */
class WorkspaceManager(context: Context) {

    private val workspaceRoot: File = File(context.filesDir, "wasti_workspace").canonicalFile

    init {
        if (!workspaceRoot.exists()) {
            workspaceRoot.mkdirs()
        }
    }

    fun getWorkspaceRootPath(): String = workspaceRoot.canonicalPath

    /**
     * Resolves and validates a relative or absolute path against the canonical workspace root.
     * Uses canonical path resolution and parent-chain verification to prevent:
     * - Directory traversal escaping workspace
     * - Absolute path escaping workspace
     * - Sibling path prefix attacks (e.g. workspace_evil)
     * - Symlink escaping workspace
     */
    fun resolvePathSafely(relativePath: String): Result<File> {
        return try {
            val targetFile = if (File(relativePath).isAbsolute) {
                File(relativePath).canonicalFile
            } else {
                File(workspaceRoot, relativePath).canonicalFile
            }

            if (!isWithinWorkspace(targetFile)) {
                Result.failure(SecurityException("Access denied: path '${targetFile.canonicalPath}' escapes workspace boundary '${workspaceRoot.canonicalPath}'"))
            } else {
                Result.success(targetFile)
            }
        } catch (e: Exception) {
            Result.failure(SecurityException("Invalid workspace path: ${e.message}", e))
        }
    }

    private fun isWithinWorkspace(targetFile: File): Boolean {
        var current: File? = targetFile.canonicalFile
        val canonicalRoot = workspaceRoot.canonicalFile
        while (current != null) {
            if (current == canonicalRoot) {
                return true
            }
            current = current.parentFile
        }
        return false
    }

    fun fileExists(relativePath: String): Boolean {
        val resolved = resolvePathSafely(relativePath).getOrNull() ?: return false
        return resolved.exists()
    }

    fun readFile(relativePath: String): Result<String> {
        return resolvePathSafely(relativePath).mapCatching { file ->
            if (!file.exists() || !file.isFile) {
                throw NoSuchFileException(file, null, "File does not exist or is not a regular file")
            }
            file.readText(StandardCharsets.UTF_8)
        }
    }

    fun writeFile(relativePath: String, content: String): Result<Unit> {
        return resolvePathSafely(relativePath).mapCatching { file ->
            val parent = file.parentFile
            if (parent != null && !parent.exists()) {
                parent.mkdirs()
            }
            file.writeText(content, StandardCharsets.UTF_8)
        }
    }

    fun createDirectory(relativePath: String): Result<Unit> {
        return resolvePathSafely(relativePath).mapCatching { dir ->
            if (!dir.exists()) {
                val created = dir.mkdirs()
                if (!created && !dir.exists()) {
                    throw IllegalStateException("Failed to create directory at ${dir.canonicalPath}")
                }
            }
        }
    }

    fun listDirectory(relativePath: String): Result<List<String>> {
        return resolvePathSafely(relativePath).mapCatching { dir ->
            if (!dir.exists() || !dir.isDirectory) {
                throw NoSuchFileException(dir, null, "Directory does not exist or is not a directory")
            }
            dir.list()?.toList() ?: emptyList()
        }
    }

    /**
     * Stage 3 Task 5: Autonomous Workspace Project Creation
     */
    fun createProjectStructure(projectName: String): Result<Unit> {
        val root = "projects/$projectName"
        return try {
            createDirectory("$root/src/main/kotlin")
            createDirectory("$root/src/test/kotlin")
            createDirectory("$root/docs")
            writeFile("$root/README.md", "# $projectName\nAutonomous project generated by Wasti AI OS.")
            writeFile(
                "$root/build.gradle.kts",
                "plugins {\n    kotlin(\"jvm\") version \"2.0.21\"\n}\n"
            )
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    /**
     * Stage 3 Task 5: Workspace Snapshot Creation
     */
    fun createSnapshot(snapshotId: String): Result<String> {
        val snapshotsDir = File(workspaceRoot, ".snapshots/$snapshotId")
        return try {
            if (snapshotsDir.exists()) {
                snapshotsDir.deleteRecursively()
            }
            snapshotsDir.mkdirs()

            // Copy workspace files excluding .snapshots
            copyDirectoryExcludingSnapshots(workspaceRoot, snapshotsDir)
            Result.success(snapshotId)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    fun restoreSnapshot(snapshotId: String): Result<Unit> {
        val snapshotsDir = File(workspaceRoot, ".snapshots/$snapshotId")
        return try {
            if (!snapshotsDir.exists()) {
                throw NoSuchFileException(snapshotsDir, null, "Snapshot $snapshotId does not exist")
            }

            // Clear current workspace files excluding .snapshots
            workspaceRoot.listFiles()?.forEach { file ->
                if (file.name != ".snapshots") {
                    file.deleteRecursively()
                }
            }

            // Restore from snapshot
            snapshotsDir.listFiles()?.forEach { file ->
                val target = File(workspaceRoot, file.name)
                if (file.isDirectory) {
                    file.copyRecursively(target, overwrite = true)
                } else {
                    file.copyTo(target, overwrite = true)
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    fun listSnapshots(): List<String> {
        val snapshotsDir = File(workspaceRoot, ".snapshots")
        if (!snapshotsDir.exists()) return emptyList()
        return snapshotsDir.list()?.toList() ?: emptyList()
    }

    private fun copyDirectoryExcludingSnapshots(source: File, target: File) {
        source.listFiles()?.forEach { file ->
            if (file.name != ".snapshots") {
                val dest = File(target, file.name)
                if (file.isDirectory) {
                    dest.mkdirs()
                    copyDirectoryExcludingSnapshots(file, dest)
                } else {
                    file.copyTo(dest, overwrite = true)
                }
            }
        }
    }
}
