package com.example.ui.screens

import android.app.Activity
import android.content.Intent
import android.speech.RecognizerIntent
import android.speech.tts.TextToSpeech
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.*
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.*
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalFocusManager
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.db.AgentEntity
import com.example.data.db.ConversationEntity
import com.example.data.db.MessageEntity
import com.example.data.voice.VoiceManager
import com.example.data.voice.provider.STTState
import com.example.data.device.WastiIntentParser
import com.example.ui.components.CodeBlockView
import com.example.ui.components.UniversalTaskTimelineStepper
import com.example.ui.components.WastiVoiceCallModal
import com.example.ui.components.ReverseAppStoreIntentCard
import com.example.ui.components.IntentExecutionStep
import com.example.ui.components.IntentStepStatus
import com.example.util.WastiSpeechSanitizer
import com.example.security.BiometricSecurityManager
import com.example.data.core.WastiExperienceMode
import com.example.security.findFragmentActivity
import android.widget.Toast
import kotlinx.coroutines.launch
import java.util.Locale

/* Existing ChatWorkspaceScreen implementation is preserved verbatim. */
